# Generated by Django 6.0.7 on 2026-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('client', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
