# Generated by Django 6.0.7 on 2026-07-26 20:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='type',
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project_cover'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='project_gallery'),
        ),
    ]
