# Generated by Django 6.0.7 on 2026-07-24 09:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(choices=[('Material Directory', 'Material Directory'), ('Materials & Colour', 'Materials & Colour')], default='Material Directory', max_length=50)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'brand'],
            },
        ),
    ]
